### ISSUE TITLE
host on web

### ISSUE THREAD

**Issue by jayvgithub** [tarush-r/Torrent-Streamer#1]
can you provide or add some info to host in website

**Comment by tarush-r** [comment]
Streaming from the magnet link happens on the server side and that stream is sent to the client, so currently this architecture is not suitable for hosting since it will use up a lot of server resources. I tried to stream directly on the client side angular but was not able to run the npm modules in the browser. Update me if you find a way to stream directly in the browser

**Comment by jayvgithub** [comment]
> Streaming from the magnet link happens on the server side and that stream is sent to the client, so currently this architecture is not suitable for hosting since it will use up a lot of server resources. I tried to stream directly on the client side angular but was not able to run the npm modules in the browser. Update me if you find a way to stream directly in the browser

the same i want to host server server side streaming and client server to watch frontend for users 
how can i contact you mail or skype or telegram

**Comment by tarush-r** [comment]
> > Streaming from the magnet link happens on the server side and that stream is sent to the client, so currently this architecture is not suitable for hosting since it will use up a lot of server resources. I tried to stream directly on the client side angular but was not able to run the npm modules in the browser. Update me if you find a way to stream directly in the browser
> 
> the same i want to host server server side streaming and client server to watch frontend for users
> how can i contact you mail or skype or telegram

you can contact me on telegram @tarushrajput
